%% Experimental Data Plotting
% This script takes the CSV files generated by the oscilloscopes and
% creates bode plots.
% They are scatter plots, so to change the thickness of the lines change
% the size parameter in the scatter function.
% Colour can also be changed in the same function.

% ----- Clear Commands ----- %
clc;              % Clear the Command Window
clear;            % Clear variables
close all;        % Close all figures

fs = 7800; % Stopband frequency, for placing a marker on the plots

%% Stage A
stageAexp = readtable("STAGEA.CSV"); % Converts CSV to table
stageAexpTitle = 'Stage A Experimental Results';
exp_bode_plot(fs, stageAexp, stageAexpTitle, false, true);

%% Stage B
stageBexp = readtable("STAGEB.CSV"); % Converts CSV to table
stageBexpTitle = 'Stage B Experimental Results';
exp_bode_plot(fs, stageBexp, stageBexpTitle, false, true);

%% Stage C
stageCexp = readtable("STAGEC.CSV"); % Converts CSV to table
stageCexpTitle = 'Stage C Experimental Results';
exp_bode_plot(fs, stageCexp, stageCexpTitle, false, false);

%% Microphone Output to Stage C Output
in2coutExp = readtable("IN2COUT.CSV"); % Converts CSV to table
in2coutExpTitle = 'Low Pass Filter Experimental Results';
exp_bode_plot(fs, in2coutExp, in2coutExpTitle, true, true);

%% Microphone Output to Amplifier Output
in2outExp = readtable("IN2OUT.CSV"); % Converts CSV to table
in2outExpTitle = 'Analog Conditioning Circuit Experimental Results';
exp_bode_plot(fs, in2outExp, in2outExpTitle, true, true);
%% Function
function fig = exp_bode_plot(stopband_freq, data_table, plot_title, markers, gain_marker)
    fig = figure;
    title(plot_title);

    % Set log scale for x-axis and enable hold
    set(gca, 'XScale', 'log');
    hold on;

    % Use yyaxis to set up dual y-axes
    yyaxis left
    gainPlot = scatter(data_table.FrequencyInHz, data_table.GainInDB, ...
                       3, "blue", "filled", ...
                       'DisplayName', 'Gain (dB)');
    ylabel('Gain (dB)');
    ylim([-60 50]);
    yticks([-60 -50 -40 -30 -20 -10 0 10 20 30 40 50]);

    passband_min_freq = 300;
    passband_max_freq = 3600; % Tune this just below the passband freq that is visible
    % Find indices corresponding to the passband frequency range
    passband_indices = find(data_table.FrequencyInHz >= passband_min_freq & ...
                            data_table.FrequencyInHz <= passband_max_freq);

    % Gain values in passband
    passband_gains = data_table.GainInDB(passband_indices);
    
    % Max Passband Gain marker
    if gain_marker == true
        max_passband_gain = max(passband_gains);
        max_passband_gain_marker_index = ...
                    find(data_table.GainInDB == max_passband_gain, 1, 'last');
        max_gain_markerPlot = ...
                scatter(data_table.FrequencyInHz(max_passband_gain_marker_index), ...
                        data_table.GainInDB(max_passband_gain_marker_index), ...
                        15, 'go', 'filled', ...
                        'DisplayName', ...
                        sprintf('Max Gain: %.2f dB at %.2f Hz', ...
                        data_table.GainInDB(max_passband_gain_marker_index), ...
                        data_table.FrequencyInHz(max_passband_gain_marker_index)) ...
                        );
    end

    % Add markers at stopband frequency and passband frequency
    if markers == true
        % Passband frequency  
        % Find the lowest gain passband
        lowest_passband_gain = min(passband_gains);
    
        % Get the first index that is lower than the lowest passband gain
        passband_marker_index = find(data_table.GainInDB < lowest_passband_gain & ...
                                    data_table.FrequencyInHz >= passband_max_freq, ...
                                    1, 'first');
    
        % Add a marker at this point
        passband_markerPlot = scatter(data_table.FrequencyInHz(passband_marker_index), ...
                                      data_table.GainInDB(passband_marker_index), ...
                                      15, 'ko', 'filled', ...
                                      'DisplayName', ...
                                      sprintf('Passband: %.2f dB at %.2f Hz', ...
                                      data_table.GainInDB(passband_marker_index), ...
                                      data_table.FrequencyInHz(passband_marker_index) ...
                                      ));

        % Stopband Frequency
        stopband_marker_index = find(data_table.FrequencyInHz < stopband_freq, 1, 'last');
        stopband_markerPlot = scatter(data_table.FrequencyInHz(stopband_marker_index), ...
                             data_table.GainInDB(stopband_marker_index), ...
                             15, 'ro', 'filled', ...
                             'DisplayName', ...
                             sprintf('Stopband: %.2f dB at %.2f Hz', ...
                             data_table.GainInDB(stopband_marker_index), ...
                             data_table.FrequencyInHz(stopband_marker_index) ...
                             ));
    end
    
    yyaxis right
    phasePlot = scatter(data_table.FrequencyInHz, ...
                        data_table.PhaseIn_, ...
                        3, "magenta", "filled", ...
                        'DisplayName', 'Phase (degrees)');

    max_passband_gain = max(passband_gains);
    lowest_passband_gain = min(passband_gains);
    ripple = abs(max_passband_gain - lowest_passband_gain);
    ripple_in_legend = scatter(0, 0, 'white', 'DisplayName', ...
                               sprintf('Ripple: %.2f dB', ripple));
    
    ylabel('Phase (degrees)');
    ylim([-180 180]);
    yticks([-180 -90 0 90 180]);

    % Common X-axis
    xlabel('Frequency (Hz)');
    xlim([10 10000]);

    % Grid and minor ticks
    grid on;
    ax = gca;
    ax.YMinorTick = 'on';
    ax.YMinorGrid = 'on';
    ax.XMinorTick = 'on';
    ax.XMinorGrid = 'on';

    % Set both y-axes to black, they default to blue and orange
    ax.YAxis(1).Color = 'k'; % Left axis
    ax.YAxis(2).Color = 'k'; % Right axis

    % legend handles must be in the order you want them shown
    if markers == true && gain_marker == true
        legend([gainPlot, phasePlot, ...
                stopband_markerPlot, ...
                passband_markerPlot, ...
                max_gain_markerPlot, ...
                ripple_in_legend], ...
               'Location', 'southwest');
    elseif markers == false && gain_marker == true
            legend([gainPlot, phasePlot, ...
                max_gain_markerPlot], ...
               'Location', 'southwest');
    else
        legend([gainPlot, phasePlot,], 'Location', 'southwest');
    end

    % Control size and aspect ratio of the plot for consistency
    fig.Units = 'inches';
    fig.Position = [1 1 12 4];  % Plot size, x-pos, y-pos, x-width, y-width

    hold off;
end




    
